CREATE TABLE IF NOT EXISTS contents (
    lesson INTEGER NOT NULL,
    seq INTEGER NOT NULL,
    french TEXT NOT NULL,
    english TEXT NOT NULL,
    PRIMARY KEY (lesson, seq)
);

INSERT INTO contents (lesson, seq, french, english) VALUES
(1,1,'Bonjour Jeanne, comment allez-vous ?','Hello, Jeanne. How are you?'),
(1,2,'Bien, et vous ?','Well, and you?'),
(1,3,'Ça va très bien, merci.','Very Well, thanks.'),
(1,4,'Je veux présente ma fille, Chloé.','Let me introduce my daughter, Chloé.'),
(1,5,'Bonjour, Chloé. Comment ça va ?','Hello Chloé. How are you?'),
(2,1,'Monsieur, madame, vous désirez ?','Sir, madam, what would you like?'),
(2,2,'Deux cafés et deux croissants, s''il vous plaît.','Two coffees and two croissants, please.'),
(2,3,'Non, je préfère une tartine beurrée pour le petit-déjeuner.','No, I prefer a slice of butter bread for breakfast.'),
(2,4,'Donc, deux expressos, un croissant et une tartine ?','So to espressos, one croissant, and one slice of buttered bread?'),
(2,5,'Oui, c''est ça. Le croissant est pour moi et la tartine pour elle.','Yes, that''s right. The croissant is for me and the bride is for her.'),
(3,1,'Je me présente : je m''appelle Sophie Mercier.','Let me introduce myself: I am Sophie Mercier.'),
(3,2,'Et voici mon ami Loïc Le Gall. Il est breton.','And here is my friend Loïc Le Gall. He is Breton.'),
(3,3,'Et vous, êtes-vous bretonne aussi ?','And you, are you Breton, too?'),
(3,4,'Pas du tout, je suis de Nîmes, dans le Midi de la France.','Not at all, I am from Nîmes, in the south of France.'),
(3,5,'Mais maintenant nous sommes parisiens.','But now we are Parisians.'),
(4,1,'Pardon, est-ce que vous avez l''heure ?','Excuse me, do you have the time?'),
(4,2,'Je n''ai pas de montre mais je pense qu''il est midi dix.','I don''t have a watch, but I think it is ten past noon.'),
(4,3,'Mais comment le savez-vous?','But how do you know that?'),
(4,4,'Parce que j''ai rendez-vous avec ma femme à midi','Because I''m meeting my wife at noon'),
(4,5,'et elle a toujour dix minutes de retard !','and she is always ten minutes late!'),
(5,1,'Excusez-moi, je cherche le métro Saint-Michel.','Excuse me, I''m looking for the Saint-Michel metro station.'),
(5,2,'Désolée, madame, je ne suis pas d''ici.','Sorry, madam, I''m not from here.'),
(5,3,'Mais attendez une minute, j''ai un plan de la ville.','But wait a minute, I have a map of the city.'),
(5,4,'Voilà : traversez le boulevard et tournez à gauche à la fontaine.','Here we are: cross the boulevard and turn left at the fountain.'),
(5,5,'Merci beaucoup pour votre aide !','Thanks very much for your help!'),
(6,1,'Bonsoir monsieur, bonsoir madame. Bienvenue à l''Hôtel Molière.','Good evening, sir: good evening, madam. Welcome to the Molière Hotel.'),
(6,2,'Bonsoir, nous avons une chambre réservée pour deux nuits.','Good evening, we have a room reserved for two nights.'),
(6,3,'Quel est votre nom, s''il vous plaît ?','What is your name, please?'),
(6,4,'Je m''appelle Bailly : B-A-I deux L-Y. Alain.','My name is Bailly: B-A-I-double-L-Y. Alain.'),
(6,5,'Absolument : une grande chambre avec un grand li et une salle de bains.','Absolutely: a large room with a double bed and a bathroom.'),
(6,6,'C''est au quatrième étage. Voici la clé.','It''s on the fourth floor. Here''s the key.'),
(6,7,'Où sont vos bagages ?','Where are your bags?'),
(8,1,'Bonjour mademoiselle, est-ce que votre père est à la maison?','Good morning, miss. Is your father at home?'),
(8,2,'Non, monsieur ; il est au bureau aujourd''hui.','No, sir; he is at the office today.'),
(8,3,'À quelle heure est-ce qu''il rentre après le travail ?','What time does he come back after work?'),
(8,4,'Oh, pas avant huit heures normalement.','Oh, not before 8 o''clock normally.'),
(8,5,'Vous voulez l''adresse de son bureau ?','Do you want the address of his office?'),
(8,6,'Oui, s''il vous plaît.','Yes, please.'),
(8,7,'Attendez un moment, je cherche mon carnet d''adresses.','Wait a moment, I''m looking for my address book.'),
(8,8,'Voilà. Sept rue Marbeuf, dans le huitième.','There it is. 7 street Marbeuf, in the 8th'),
(8,9,'Merci beaucoup, mademoiselle. Au revoir.','Thank you very much, miss. Goodbye.'),
(8,10,'De rien, monsieur. Au revoir.','You''re welcome, sir. Goodbye.'),
(9,1,'Ce monsieur s''appelle Jérôme Laforge et cette dame est sa femme.','This gentleman is called Jérôme Laforge and this lady as his wife.'),
(9,2,'Ils sont à la mairie pour demander une nouvelle carte d''identité pour leur fils.','They are at the town hall to ask a new identity card for their son.'),
(9,3,'Quel âge a cet enfant ?','How old is this child?'),
(9,4,'Il a huit ans, monsieur.','He is eight years old, sir.'),
(9,5,'Et il s''appelle Laforge ? Est-ce que c''est votre enfant ?','And he''s called Laforge? Is it he your child?'),
(9,6,'Oui, monsieur.','Yes, sir.'),
(9,7,'Bien. Et il habite chez vous ?','Fine. And he lives with you.'),
(9,8,'Mais évidemment, avec moi et sa mère !','Obviously, with me and his mother.'),
(10,1,'D''accord. Je fais mon travail, c''est tout.','OK. I''m doing my job, that''s all.'),
(10,2,'Est-ce que vous avez le formulaire B-52 ?','Do you have the form B-52?'),
(10,3,'Oui monsieur, nous l''avons.','Yes, sir, we have it.'),
(10,4,'Et l''imprimé A-65 ?','And the printed form A-65?'),
(10,5,'Ça aussi, nous l''avons.','That also, we have it.'),
(10,6,'Ah bon ? Mais est-ce que vous avez son passeport ?','Oh, really(good),? But do you have his passport?'),
(10,7,'Bien sûr. Nous avons même sa photo.','Of course we have even his photo.'),
(10,8,'Très bien. Alors je vous fais la carte. Voilà.','Very well. So I will do you the card. Here it is.'),
(10,9,'Réglez à la caisse, s''il vous plaît.','Pay at the cash desk, please.'),
(10,10,'Zut ! Je ne trouve pas mon portefeuille !','Damn! I cannot find my wallet!'),
(11,1,'Pourquoi allons-nous au marché ? Il est trop cher.','Why we are going to the market? It''s too expensive.'),
(11,2,'Parce que tous les placards sont vides !','Because all the cupboardz are empty.'),
(11,3,'Nous avons besoin de tout : de fruits et de légumes,','We need everything: fruit, vegetables,'),
(11,4,'mais aussi de pain, de fromage, de beurre, de crème, de jambon, et...','but also bread, butter, cream and...'),
(11,5,'Bon, je comprends. Il n''y a rien à manger. Allons-y.','OK, I understand. There is nothing to eat. Let''s go.'),
(11,6,'Bonjour madame. qu''est-ce que je peux faire pour vous ?','Good morning, madam. What can I do for you?'),
(11,7,'Je vais acherter une livere de cerises, un kilo de pommes,','I''m going to buy a pound of cherries, a kilo of apples,'),
(11,8,'trois cents grammes de champinons, s''ils ne sont pas trop chers,','300 grams of mushrooms, if they are not too expensive,'),
(11,9,'quelques bananes, deux kilos de pommes de terre et un peu de lait frais.','a few bananas, two kilo of potatoes and a little fresh milk.'),
(12,1,'Et avec ceci ? Vous voulez des fraises, peut-étre ?','And with that? Do you want some strawberries, perhaps?'),
(12,2,'Est-ce que je peux les goûter ?','Can I taste them?'),
(12,3,'Allez-y. N''hésitez pas ! Toutes mes fraises sont bio.','Go ahead. Don''t hesitate. All my strawberries are organic.'),
(12,4,'Mm, c''est vrai, elles sont vraiment délicieuses. Elles sont à combien ?','Mm. It''s true. They are really delicious. How much are they?'),
(12,5,'Le prix ? Elles ne sont pas chères. Seulement quinze euros le kilo.','The price? They are not expensive, only 15 euros a kilo.'),
(12,6,'Non, c''est trop cher. J''ai tout ce que je veux pour l''instant.','No, it''s too expensive. I have all that I want for the time being.'),
(12,7,'Alors, ça vous fait vingt-six euros soixante s''il vous plaît.','Right, that makes 26 euros 60 please.'),
(12,8,'Voilà trente.','Here is 30.'),
(12,9,'Et voici votre monnaie. Bonne journée.','And here''s your change. Have a good day.'),
(13,1,'Louise, Lucas ! Venez voir mon cadeau d''anniversaire !','Louise, Lucas! Come and see my birthday present!'),
(13,2,'qu''est-ce que c''est ?','What is it?'),
(13,3,'Vous ne savez pas ?','Don''t you know ?'),
(13,4,'C''est un nouveau téléphone.','it''s a new phone.'),
(13,5,'Il fait absolument tout.','It does absolutely everything.'),
(13,6,'Vous pouvez envoyer des message, commander un repas,','You can send message, order a meal,'),
(13,7,'payer vos courses, écouter la musique, regarder des vidéos...','pay for your shopping, listen to music, watch videos.'),
(13,8,'et vous pouvez même parler à quelqu''un.','and you can even speak to someone.'),
(13,9,'Est-ce que je peux l''essayer ?','Can I try it?'),
(13,10,'Non, malheureusement. Ce n''est pas possible.','No, unfortunately, it''s not possible.'),
(13,11,'Il ne marche pas ?','Isn''t it working?'),
(13,12,'Je ne connais pas le code secret.','I don''t know the pass code.'),
(15,1,'Bonjour mesdames, bonjour mesdemoiselles, bonjour messieurs.','Good morning ladies, good morning young ladies, good morning gentlemen.'),
(15,2,'Mon nom est Michèle Laroche et je suis votre guide ce matin.','My name is Michèle Laroche and I am your guide this morning.'),
(15,3,'Nous traversons actuellement la place de la Concorde.','We are crossing at present (currently), Concorde Square (place of the Concorde),.'),
(15,4,'Devant vous, vous pouvez voir le Louvre et, à droite, la Tour Eiffel.','In front of you, you can see the Louvre and, on (to), [the] right, the Eiffel Tower.'),
(15,5,'s''il vous plaît, madame, où sont… ?','Please, madam, where are…'),
(15,6,'Un instant. Laissez-moi terminer, s''il vous plaît.','Just a minute (one instant),. Let me finish please.'),
(15,7,'Mais c''est très important : je ne peux pas attendre cet après-midi.','But it''s very important: I can''t wait [until] this afternoon.'),
(15,8,'Eh bien, qu''est-ce que vous voulez savoir ?','Well, what do you want to know?'),
(15,9,'Où sont les toilettes ? ','Where is the toilet? '),
(16,1,'Comparé à d''autres capitales, comme Moscou ou Pékin, Paris n''est pas très grand.','Compared to some other capitals, like Moscow or Beijing, Paris is not very big.'),
(16,2,'Mais la région parisienne, c''est-à-dire la ville et sa banlieue, est grande comme Londres.','But the Parisian region, that (it), is to say the city and its suburb(s), is as big as London.'),
(16,3,'On l''appelle La Ville Lumière, avec ses grands monuments et ses longues avenues.','It is called (one it-calls), The City [of] Light, with its great monuments and long avenues.'),
(16,4,'ses grandes églises et ses vieilles rues.','its grand churches and its old streets.'),
(16,5,'Regardez là-bas : ce bâtiment superbe est l''Opéra,','Look over there: this superb building is the Opera,'),
(16,6,'construit par le grand architecte Charles Garnier.','built by the great architect Charles Garnier.'),
(16,7,'Derrière, vous avez les grands magasins, et, en face, on voit le Café de la Paix.','Behind, you have the major department stores (big shops), and, opposite, you can see (one sees), the Café de la Paix (Peace Café),.'),
(16,8,'C''est un bon endroit pour une photo, et la lumière est bonne aujourd''hui.','It''s a good spot (place), for a photo, and the light is good today.'),
(16,9,'Vous pouvez faire beaucoup de belles images.','You can take (make), lots of beautiful pictures.'),
(16,10,'Si vous voulez, vous pouvez descendre du bus ici, à côté de l''arrêt.','If you want, you can get off (descend from), the bus here, next to the stop.'),
(17,1,'Dites-moi, quels sont vos projets pour demain ?','Tell me, what are your plans (projects), for tomorrow?'),
(17,2,'Il y a une nouvelle exposition à La Piscine. J''ai très envie de voir.','There is a new exhibition at La Piscine (the Swimming Pool), that I really want (have very envy), to see.'),
(17,3,'Vous voulez venir avec moi ?','Do you want to come with me?'),
(17,4,'Je ne suis pas sûr ; je dois aller chez le médecin cet après-midi.','I''m not sure: I have to go to the doctor [in] the [this] afternoon.'),
(17,5,'À quelle heure est votre rendez-vous ?','(At), What time is your appointment?'),
(17,6,'Assez tard : vers seize ou dix-sept heures. Ça ne laisse pas beaucoup de temps.','Quite late: around (towards), four (16 hours), or five (17 hours), o''clock. That does not leave a lot of time.'),
(17,7,'Mais on peut y aller aujourd''hui si vous voulez.','But we can go (there), today if you want.'),
(17,8,'Pourquoi pas ? Quelle heure est-il maintenant ?','Why not? What time is it now?'),
(17,9,'Il est presque treize heures : très précisément, midi quarante-cinq.','It''s almost 1 o''clock (nearly 13 hours),: very precisely, 12:45 (midday forty-five),.'),
(17,10,'Donc nous avons le temps : l''expo ferme à dix-huit heures.','So we have (the), time: the exhibition closes at 6 o''clock (18 hours),.'),
(17,11,'Quelles sont les choses à voir ? Et quel est le titre de cette exposition ?','What are the things to see? And what is the title of this exhibition?'),
(17,12,'"Le Sujet, l''objet et l''eau". Très profond, mais pas très clair !','"The Subject, the Object and (the), Water". Very deep (profound), but not very clear!'),
(18,1,'Bonjour Monsieur Castille. Nous voudrions prendre un rendez-vous avec vous.','Good morning Mr Castille. We want to make an appointment with you.'),
(18,2,'Est-ce que vous pouvez venir le mardi vingt-deux mars ? ','Can you come [on] (the), Tuesday [the] twenty-second (22), [of] March'),
(18,3,'Je suis libre entre neuf heures et onze heures, ou plus tard dans la journée.','I''m free between nine o''clock and eleven o''clock, or later in the day.'),
(18,4,'Non, nous sommes pris toute la semaine, du lundi vingt, et un au vendredi vingt-cinq.','No, we are taken the whole week, from Monday the twenty-first to Friday the twenty-fifth.'),
(18,5,'Avez-vous une autre date ? En mai, par exemple ?','Do you have another date? In May, for example?'),
(18,6,'Je regrette : mai n''est pas possible, à cause des ponts.','I''m sorry, May is not possible, because of the long weekends.'),
(18,7,'Je ne peux pas vous voir avant le mercredi trente juin. Mon emploi du temps est très chargé.','I can''t see you before Wednesday the thirtieth of June. My schedule is very full.'),
(18,8,'Mais nous, nous sommes en voyage en juin et juillet.','But we are travelling in June and July.'),
(18,9,'Moi, je suis en vacances au mois d''août. Je prends l''avion le jeudi douze pour aller aux États-Unis.','Me, I''m on holiday in the month of August. I am flying to the United States on Thursday the twelfth.'),
(18,10,'Septembre est hors de question à cause de la rentrée scolaire.','September is out of the question because of the new academic year.'),
(18,11,'Et en octobre j''ai déjà trois conférences et un stage de formation. Novembre ?','And in October I already have three lectures and a training course. November?'),
(18,12,'Ce n''est pas un bon mois : mes parents passent trois semaines chez nous.','It''s not a good month: my parents are spending three weeks with us.'),
(18,13,'Attendez : je peux vous proposer le samedi vingt-cinq décembre ou le dimanche vingt-six.','Wait: I can offer you Saturday the twenty-fifth of December or Sunday the twenty-sixth.'),
(18,14,'Mon agenda est enfin vide !','My diary is finally empty at last!'),
(19,3,'Pour combien de personnes ?','For how many (of), people?'),
(19,4,'Environ une trentaine : il y a la famille, la belle-famille, des copains.','About thirty: there is the family, the (beautiful), family-in-law, some mates.'),
(19,5,'Je veux quelque chose de beau et pas trop cher.','I want something lovely (handsome), and not too expensive.'),
(19,6,'C''est pour quand cette fête ? Pas à la fin de l''année, j''espère ?','When (it''s for when), is this party? Not at the end of the year, I hope?'),
(19,7,'Nous fermons entre Noël et le Nouvel An.','We close between Christmas and the New Year.'),
(19,8,'Pas de problème : c''est pour la soirée du trente juin, jusqu''à minuit.','No problem: it''s for the evening of the thirteenth (of), June, until midnight.'),
(19,9,'Voyons : j''ai une belle salle pour une cinquantaine de personnes. C''est un bel endroit pour une fête.','Let''s see: I have a lovely room for about fifty people. It''s a great place for a party.'),
(19,10,'Ça coûte combien ? Je n''ai pas un gros budget.','How much does it cost (that costs how much),? I don''t have a big budget.'),
(19,11,'Alors j''ai quelque chose de plus petit et moins cher :','Then I have something (of), smaller (more small), and less expensive:'),
(19,12,'le placard à balais : c''est gratuit !','the broom cupboard: it''s free!'),
(19,1,'Hôtel Sacré Cœur. Comment est-ce que je peux vous aider ?','Hotel Sacré Cœur. How can I help you?'),
(19,2,'J''organise une fête pour mon anniversaire et je veux louer une salle.','I[am] organising a party for my birthday and I want to rent a room.'),
(20,1,'Le sujet de l''émission Carte blanche cette semaine est "Un monde idéal".','The subject of the programme Carte Blanche (card white) this week is "An ideal world."'),
(20,2,'Nous avons posé la question suivante aux ambassadeurs de quatre pays','We (have), put the following question to the ambassadors of four countries:'),
(20,3,'le Japon, l''Inde, les États-Unis et la France','(the), Japan, (the), India, (the), United States and (the), France.'),
(20,4,'“Que voulez-vous pour Noël, Monsieur l''Ambassadeur ?”','What do you want for Christmas, Mr (the), Ambassador?”'),
(20,5,'Voici leurs réponses, dans l''ordre.','Here are their answers, in (the), order.'),
(20,6,'L''ambassadeur japonais veut “du bonheur, de la paix et des droits humains”.','The Japanese ambassador wants “(of the), happiness, (of the), peace and (of the), human rights.”'),
(20,7,'Son collègue indien veut “de la santé et de l''éducation pour tout le monde”.','His Indian colleague wants “(of the), health and (of the), education for everyone (all the world),.'),
(20,8,'L''Américain veut “des emplois, de l''argent et du bien-être pour son pays”.','The American wants “(of the), jobs, (of the), money and (of the), well-being (well-to-be), for his country.'),
(20,9,'Mais la réponse de l''ambassadeur français est la plus intéressante.','But the answer of the French ambassador is the most interesting.'),
(20,10,'Ah bon ? qu''est-ce qu''il veut ?','REALLY (ah good),? WHAT does he want?'),
(20,11,'Des chocolats, du vin blanc et de la crème fraîche.','(of the), Chocolates, (of the), white wine and (of the), fresh cream.'),
(20,12,'Ce n''est pas vrai ! Il est honnête, au moins !','I don''t believe it! (it is not true), He''s honest, at least!'),
(22,1,'Je n''aime pas les jeux de hasard, parce qu''ils sont tous risqués. Et vous ?','I don''t like (the), games of chance, because they''re all risky. And you?'),
(22,2,'Je suis comme vous. Mais il y a un jeu que j''aime bien.','I''m like you. But there is one game that I really like (like well),.'),
(22,3,'Vraiment ? Lequel ? Les machines à sous ?','Really? Which one? Slot machines (machines at pennies),?'),
(22,4,'Mais non ! Ce sont les courses de chevaux.','Not at all (but no),. It''s (it are), horse races.'),
(22,5,'Je regarde tous les journaux spécialisés, surtout un journal intitulé Mille gagnants,','I read all the specialised newspapers, especially a paper called (entitled), ''[A] Thousand Winners.'''),
(22,6,'et j''établis une petite liste.','and I make (establish), a little list.'),
(22,7,'Je réfléchis pendant quelques secondes, et quand je suis prêt,','I think (reflect), for a few seconds, and when I''m ready,'),
(22,8,'je choisis le cheval qui a une bonne chance de finir en premier.','I choose the horse that has a good chance of finishing (to finish in), first.'),
(22,9,'Puis je remplis la grille de jeu… et je croise les doigts.','Then I fill in the race card (game grid),… and I cross my (the), fingers.'),
(22,10,'Au fait, comment est-ce que vous choisissez vos chevaux ?','By the way (to-the-fact), how do you choose your horses?'),
(22,11,'qu''est-ce que vous espérez ?','And what do you hope [for]?'),
(22,12,'Je suis comme tous les joueurs ; nous avons tous la même idée :','I''m like all gamblers (players),: we all have the same idea:'),
(22,13,'gagner beaucoup d''argent et devenir très riche.','to earn (win), a lot of money and to become very rich.'),
(22,14,'Au fait, est-ce que vous pouvez me prêter cinquante euros ?','By the way, can you lend me fifty euros?'),
(22,15,'Je n''ai pas un sou.','I''m broke (I don''t have a penny),.'),
(23,1,'Bonjour, qu''est-ce que je vous sers ?','Good morning, what can I get you (what-is-it that I you serve),?'),
(23,2,'Je veux un café crème, un croque-monsieur et deux billets de loto, s''il vous plaît.','I want a white coffee (coffee cream), a toasted ham-and-cheese sandwich (''bite-sir''), and two lotto tickets, please.'),
(23,3,'Vous pouvez jouer au loto en ligne, vous savez. C''est très simple.','You can play (at), the lotto online, you know. It''s very simple.'),
(23,4,'Et il n''y a pas de queues au comptoir, comme ce matin.','And there are no queues at the counter, like this morning.'),
(23,5,'Je sais, mais je préfère venir ici : l''ambiance est sympa.','I know, but I prefer to come here: the atmosphere is nice.'),
(23,6,'Je saisis l''occasion pour quitter mon appartement et voir d''autres gens.','I take (seize), the opportunity to get out of (to leave), my flat and (to see), seeing other people.'),
(23,7,'J''ai des clients qui viennent jouer tous les jours.','I have customers who come every day.'),
(23,8,'Dites-moi : avez-vous un secret pour le loto ?','Tell (say), me, do you have a secret for the lotto?'),
(23,9,'Toutàfait. Je joue toujours les mêmes numéros :','Absolutely (all to fact),. I play (play always), the same numbers:'),
(23,10,'tous ceux finissant par quatre, plus le soixante-deux, le quarante-trois, le dix-sept, et le cinquante-cinq,','all those finishing in (by), 4, plus (the), 62, (the), 43, (the), 17 and (the), 55,'),
(23,11,'ma date de naissance : le vingt-trois, douze, soixante-neuf,','my birth date: (the), 23-12-69'),
(23,12,'et, évidemment, le treize, mon chiffre préféré.','and, of course (evidently), (the), 13, my favourite number.'),
(23,13,'Avec ça, vous réussissez à gagner ? Je vous applaudis !','With that, you manage (succeed), to win? I applaud you!'),
(23,14,'Non, pas vraiment, mais j''investis pour l''avenir. Je vais gagner un de ces jours !','No, not really, but I''m investing for the future. I''m going to win one day!'),
(24,1,'Asseyez-vous, mademoiselle. qu''est-ce qui ne va pas ?','Sit down, miss. What''s the matter (what is-it-that not go),?'),
(24,2,'Je ne vais pas bien du tout, docteur.','I''m not well at all, doctor.'),
(24,3,'J''ai mal à la tête, mal aux oreilles et mal au genou droit,','I have a headache (bad at the head), an earache (bad at the ears), and a pain (bad at), in my right knee'),
(24,4,'et j''ai aussi de la fièvre. Est-ce que c''est grave ?','and I also have a (the), fever. Is it serious (grave),?'),
(24,5,'Eneffet, vous avez l''air fatiguée. Vous n''êtes pasen forme.','Indeed (in effect), you look (have the-air), tired. You''re not on form.'),
(24,6,'Je vais prendre votre température. Mm, vousavez trente-huit.','I''m going to take your temperature. Mm, it''s (you have), 38 [100°F].'),
(24,7,'C''estun peu élevé. Maintenant, ouvrez la bouche. Fermez.','That''s a little high. Now, open your (the), mouth. Close.'),
(24,8,'Je vais vérifier votre tension et écouter votre cœur. Respirez.','I''m going to check your blood pressure (tension), and listen [to] your heart. Breathe.'),
(24,9,'Vousavez une bonne vieille grippe, c''est tout.','You have a (good old-fashioned (good old),), flu, that''s all.'),
(24,10,'Je vous donne trois médicaments, que vous devez prendre pendant huit jours.','I''m giving you three drugs (medicines), which you must take for eight days.'),
(24,11,'D''abord, un sirop. Vous le prenez trois fois par jour : le matin, le midi et le soir.','Firstly, a syrup. You take it (it take), three times a (by), day: morning, noon and evening.'),
(24,12,'Ensuite, des comprimés. Il faut les avaler avec un grand verre d''eau.','Next, (some), pills. You have to swallow them (them swallow), with a large glass of water.'),
(24,13,'Et enfin, il y a une gélule par jour. Vous la prenez avant le dîner.','And lastly, there is one capsule a day. You take it (it take), after dinner.'),
(24,14,'Voici votre ordonnance et une feuille de maladie.','Here is your prescription and a refund form (sheet of illness),.'),
(25,1,'Il est déjà midi ! J''ai faim, et vous ?','It''s already noon. I am hungry (have hunger),. And you?'),
(25,2,'Un petit peu, mais je vous accompagne avec plaisir.','A little bit. But I''ll come with (accompany), you with pleasure.'),
(25,3,'Je connais plusieurs restaurants dans le quartier :','I know several restaurants in the neighbourhood:'),
(25,4,'il y a une pizzeria près d''ici, une crêperie dans la rue à gauche, ou une brasserie à droite de l''église.','there''s a pizzeria near here, a pancake house in the street on [the] left or a brasserie to [the] right of the church.'),
(25,5,'Laquelle est-ce que vous préférez ?','Which [one] do you prefer?'),
(25,6,'Ça m''est égal. Et vous ?','It''s [all] the same (equal), to me. And you?'),
(25,7,'La crêperie : elle est excellente et pas chère. Ça vous dit ?','The pancake house. It''s excellent and not expensive. Does that tempt you (that you speaks),?'),
(25,8,'Où est-ce que c''est ? J''espère que ce n''est pas trop loin.','Where is it? I hope that it''s not too far.'),
(25,9,'Je suis assez pressé parce que j''ai un rendez-vous à quatorze heures.','I''m in quite a hurry because I have an appointment at 2pm (14 hours),.'),
(25,10,'Non, elle est à trois cents mètres d''ici. À seulement cinq minutes à pied.','No, it''s (at), 300 metres from here. (At), only 5 minutes on (to), foot.'),
(25,11,'On va tout droit puis à droite et ensuite c''est la troisième rue à gauche.','We go (one goes), straight ahead then (to), right and afterwards it''s the third street on [the] left.'),
(25,12,'Mais je viens de penser à quelque chose : elle est fermée le lundi.','But I have just thought (I come to think), of something: it''s closed [on] Monday.'),
(25,13,'Allons à la brasserie, alors. Mais faisons vite.','Let''s go to the brasserie, then. But let''s make [it] quick.'),
(26,1,'Avez-vous une table pour deux s''il vous plaît ?','Do you have a table for two, please?'),
(26,2,'Si vous voulez bien me suivre. Est-ce que cette table vous convient ?','Follow me, please (if you want well me to-follow),. Does this table suit you?'),
(26,3,'Non. Je veux être près de la fenêtre parce que j''ai chaud.','No (it doesn''t),. I want to be close to the window because I am (have), hot.'),
(26,4,'Asseyez-vous ici. Je vous apporte le menu et la carte des vins.','Sit here. I [will] bring you the menu and the wine list (card),.'),
(26,5,'J''arrive tout de suite… Alors, vous êtes prêts ?','I''ll be right there (I-arrive all of following), … So, are you ready?'),
(26,6,'Quel menu prenez-vous : celui à vingt euros ou celui à quarante ?','Which menu are you taking: the one at 20 euros or the one at 40?'),
(26,7,'Le menu à vingt. Quel est le plat du jour ? Sinon, quelles sont les spécialités ?','The menu at 20. What is the dish of the day? If not, what are your specials (specialities),?'),
(26,8,'Il n''y en a pas. Je vous conseille de prendre l''entrecôte ou le saumon froid.','We''re out (there aren''t any),. I advise you to take the rib steak (between-rib), or the cold salmon.'),
(26,9,'Dans ce cas, deux entrecôtes s''il vous plaît.','In that case, two rib steaks, please.'),
(26,10,'Quelle cuisson pour la viande, et avec quels légumes ?','How do want the meat cooked (what cooking for the meat),? And with which vegetables?'),
(26,11,'Saignante pour tous les deux, avec des frites.','Rare (bleeding), for the two of us, with chips.'),
(26,12,'Voulez-vous boire quelque chose ? Du vin ou de la bière ?','Do you want something to drink (to drink something),? (Some), wine or (some), beer?'),
(26,13,'Juste une bouteille d''eau minérale. Nous avons soif. […]','Just a bottle of mineral water. We are thirsty (have thirst),. […]'),
(26,14,'L''addition s''il vous plaît. Est-ce que le service est compris ?','The bill please. Is the service included?'),
(26,15,'Oui, mais pas le pourboire.','Yes, but not the tip (for-drink),.'),
(27,1,'Quels hôtels sont situés à proximité de l''aéroport ?','What hotels are located (situated), close (at proximity), to the airport?'),
(27,2,'Mon vol part très tôt le samedi matin et je n''ai pas envie de le rater.','My flight leaves very early on Saturday morning and I don''t want to miss it.'),
(27,3,'Pourquoi ne pas faire une recherche sur Internet ?','Why not search online (make a research on internet),?'),
(27,4,'Bonne idée ! Je me connecte.','Good idea! I''ll log on (me connect),.'),
(27,5,'Il y a un hôtel trois étoiles juste à côté du terminal et un autre à deux kilomètres.','There''s a three-star hotel just next to the terminal and another (at), two kilometres [away].'),
(27,6,'Regardons celui qui est le plus près. Il s''appelle l''Hôtel des voyageurs.','Let''s look at the one which is the nearest (most near),. It''s called the Travellers'' Hotel.'),
(27,7,'Voici une chambre supérieure : qu''est-ce que vous en pensez ?','Here''s a superior room: what do you think of it?'),
(27,8,'Je préfère celles au premier étage : elles ont l''air plus confortables.','I prefer those on the first floor: they look more comfortable.'),
(27,9,'Celle qui est à côté de l''ascenseur est moins chère que les autres','The one which is next to the lift is less expensive than the others'),
(27,10,'mais je parie qu''elle est plus bruyante.','but I bet that it''s noisier (more noisy),.'),
(27,11,'Celles au rez-de-chaussée sont petites, à mon avis','Those on the ground floor are really small, in my opinion (at my advice),'),
(27,12,'mais les équipements sont identiques à ceux des chambres supérieures','but the facilities are identical to those of the superior rooms.'),
(27,13,'et les tarifs ne sont pas les mêmes. C''est beaucoup moins cher.','and the rates (tariffs), are not the same. It''s much less expensive.'),
(27,14,'Est-ce qu''il y a des chambres disponibles pour le vendredi soir ?','Are there [any] rooms available for the Friday night (evening),?'),
(27,15,'Mince alors ! Tout est complet. Je vais regarder le deuxième hôtel.','Drat (thin then),! Everything is full. I''ll look at the second hotel.'),
(29,1,'Salut, Louis ! Comment vas-tu ?','Hi, Louis! How are you?'),
(29,2,'Je vais très bien. Et toi, Manon ? La forme ?','I''m very well. And you, Manon? On [good] form?'),
(29,3,'Ça va, merci. qu''est-ce que tu fais ici ?','Fine, thanks. What are you doing here?'),
(29,4,'Mes courses. Je cherche une pâtisserie pour acheter une tarte ou un gâteau.','My shopping. I''m looking for a cake shop to buy a tart or a cake.'),
(29,5,'Les Mercier viennent dîner ce soir et je sais que Clém adore les pâtisseries.','The Merciers are coming [to] dinner this evening and I know that Clém loves pastries.'),
(29,6,'Je dois aussi trouver un cadeau à leur offrir parce que c''est leur anniversaire de mariage samedi prochain.','I also have to find a present to give (offer), them because it''s their wedding anniversary next Saturday.'),
(29,7,'Mais je n''ai pas d''idées précises. Je ne connais pas leurs goûts.','But I don''t have any precise ideas. I don''t know their tastes.'),
(29,8,'Est-ce que tu sais où je peux acheter quelque chose d''original ?','Do you know where I can buy something (of), original?'),
(29,9,'Il y a un centre commercial là-bas, près du bureau de poste. Tu le vois ?','There''s a shopping (commercial), centre over there, near (to), the post office.'),
(29,10,'Dedans, tu as une superbe pâtisserie qui vend des tartes délicieuses pour le dessert,','Inside, there''s (you have), a superb cake shop that sells delicious tarts for (the), dessert'),
(29,11,'et des gâteaux délicieux avec des noix, des morceaux de chocolat et de la chantilly.','and delicious cakes with walnuts, bits of chocolate and whipped cream.'),
(29,12,'Excellente idée ! Je sais que nos amis sont très gourmands.','Excellent idea! I know that our friends are very fond of food.'),
(29,13,'Et pour le cadeau, qu''est-ce que tu penses d''un tableau ?','And for the present, what do you think of a painting?'),
(29,14,'Plutôt des tisanes, pour faciliter la digestion !','Herb teas instead, to help [with] digestion.'),
(29,15,'Et pour les desserts, je vais acheter un gâteau au chocolat.','And for the desserts, I''m going to buy a chocolate cake.'),
(30,1,'Excuse-moi un instant, Juliette. Je dois répondre au téléphone.','Excuse me a second (instant), Juliette. I have to answer the phone.'),
(30,2,'Allô ? Ah, c''est toi, Antoine. Je t''entends très mal.','Hello? Ah, it''s you, Antoine. I can''t hear you very well (I hear you very badly),.'),
(30,3,'Je perds le signal. Attends, ne quitte pas.','I''m losing the signal. Wait, don''t hang up (leave),.'),
(30,4,'Reste où tu es. Je vais descendre au premier étage.','Stay where you are. I''m going to go down to the first floor.'),
(30,5,'Tu sais que nous sommes au milieu de la campagne, sans antenne de téléphone !','You know that we''re in the middle of the countryside, without [a] telephone aerial!'),
(30,6,'Voilà : est-ce que tu entends ma voix ? Je mets le haut-parleur.','There: can (is-it that), you hear my voice? I''m putting [on] the loud-(high-),speaker.'),
(30,7,'Oui, c''est bien. J''ai un truc à te demander, Stéphane.','Yes, that''s fine. I''ve got something (a thing), to ask you, Stéphane.'),
(30,8,'Vas-y. qu''est-ce que je peux faire pour toi ?','Go ahead (go there),. What can I do for you?'),
(30,9,'Peux-tu me prêter ton aspirateur ? J''en ai besoin pour nettoyer ma piscine.','Can you lend me your vacuum cleaner to clean my swimming pool?'),
(30,10,'Le magasin dans notre village n''en vend pas.','The shop in our village doesn''t (of them), sell [them].'),
(30,11,'Je promets de ne pas le perdre ! Tu peux me faire confiance.','I promise not to lose it! You can trust me (make me confidence),.'),
(30,12,'Écoute, je veux bien mais ça ne dépend pas entièrement de moi.','Listen, I''m fine with that (want well), but it doesn''t depend entirely on me.'),
(30,13,'Je vais demander à Juliette si elle en a besoin. […]','I''ll go [and] ask (to), Juliette if she (of it), needs [it]. […]'),
(30,14,'Bon, c''est d''accord si tu nous le rends avant la fin de la semaine.','Well (good), she agrees (it''s okay), if you return it [to] us before the end of the week.'),
(30,15,'Merci. Je te le rends après-demain. À tout à l''heure.','Thanks. I [will] give it back [to] you [the day] after tomorrow. See you later (to all the hour),.'),
(31,1,'Que puis-je faire pour vous, madame ?','What might I do for you, madam?'),
(31,2,'Est-ce que vous avez des bouilloires électriques ?','Do you have electric kettles?'),
(31,3,'J''en ai deux : celle-ci, à moins de cent euros,','I (of them), have two: this one here, at less than a hundred euros,'),
(31,4,'et celle-là, qui est à quatre cents euros.','and that one there, which is for (at), four hundred euros.'),
(31,5,'Mais c''est hors de prix ! Elle est en argent ?','But that''s outrageous (out of price),. Is it made of (in), silver?'),
(31,6,'Bien sûr que non. C''est un appareil très sophistiqué : il est même connecté à Internet !','Of course not. It''s a very sophisticated appliance: it''s even connected to [the] Internet'),
(31,7,'Tout le monde en parle, et j''en vends beaucoup.','Everyone is talking about them, and I sell a lot.'),
(31,8,'Mais celle à cent euros marche très bien aussi, je vous assure.','But the one for (at), a hundred euros works very well, too, I assure you.'),
(31,9,'Est-ce que vous en êtes sûr ?','Are you sure of that?'),
(31,10,'Oui, j''en suis certain. Tous mes clients en sont contents, enfin, presque tous…','Yes, I''m certain of it. All my customers (of-it), are happy, well (at last), almost all…'),
(31,11,'Bon, d''accord. Donnez-moi celle à quatre cents.','Okay, alright. Give me the one for four hundred.'),
(31,12,'Excellent choix. Je regarde sur mon ordinateur…','Excellent choice. I''m checking (looking on), my computer…'),
(31,13,'Ah, excusez-moi : nous n''en avons plus. Vous en avez besoin aujourd''hui ?','Ah, excuse me: we don''t have any more (not-of-it have more),. You need one today?'),
(31,14,'Non, j''en ai vraiment besoin rapidement. Tant pis. Merci pour votre aide.','No, I really need it quickly. Never mind. Thanks for your help.'),
(31,15,'Je vous en prie. Merci de votre visite.','You''re welcome (if you of-it pray),. Thanks for visiting.'),
(32,1,'Pourquoi est-ce que vous êtes si fatigué quand vous rentrez chez vous le soir ?','Why are you so tired when you go home [in] the evening?'),
(32,2,'Mon travail est vraiment épuisant, vous savez.','My job (work), is really exhausting, you know.'),
(32,3,'Je suis responsable d''une équipe d''une douzaine de personnes','I''m responsible for a team of around ten people'),
(32,4,'dans le service commercial d''une petite entreprise, Gagner Plus.','in the marketing department of a small company (enterprise), Gagner Plus (Earn More),.'),
(32,5,'Je connais cette société. qu''est-ce que vous y faites ?','I know that company. What do you do there (there-do),?'),
(32,6,'Nous répondons aux mails des clients : nous en recevons des centaines chaque jour.','We answer (to), emails from customers: we (of them), receive hundreds each day.'),
(32,7,'En principe, nous devons les lire systématiquement, mais ce n''est pas toujours possible.','In principle, we must read them systematically, but it''s not always possible.'),
(32,8,'Bien sûr, nous ne pouvons pas répondre à chacun d''entre eux, même si nous faisons de notre mieux.','Of course, we can''t answer each one (among them), even if we do (of), our best.'),
(32,9,'Nous savons que nous faisons quelque chose de très important.','We know that we are doing something (of), very important.'),
(32,10,'Je ne refuse jamais d''aider mes collègues : je jette un coup d''œil à leur travail','I never refuse to help my colleagues: I glance (throw a blow of eye), at their work'),
(32,11,'et je leur donne un coup de main quand je peux.','and I give them a (blow of), hand when I can.'),
(32,12,'À la fin de la journée, j''ai mal aux yeux et souvent des maux de tête.','At the end of the day, I have sore eyes and often headaches.'),
(32,13,'Je ne peux plus regarder la télé, même quand il y a quelque chose qui me plaît.','I can no longer watch the TV, even when there is something that I like (me pleases),.'),
(32,14,'Demain je vais voir le directeur et lui dire que je ne peux plus continuer comme ça.','Tomorrow I''m going to see the director and tell (say to), him that I can no longer continue like this.'),
(32,15,'Ah, vous n''êtes pas au courant ? Vous ne pouvez plus lui parler :','Ah, aren''t you aware (you aren''t at current),? You can no longer talk to him:'),
(32,16,'il vient de démissionner à cause de la fatigue.','he''s just resigned because of tiredness.'),
(33,1,'Ah, c''est toi, Margot. Entre et assieds-toi.','Ah, it''s you, Margot. Come in and sit (you), down.'),
(33,2,'Je ne vous dérange pas ? Je peux revenir si vous voulez.','I''m not disturbing (deranging), you [am I]? I can come back if you want.'),
(33,3,'Tu ne nous déranges pas du tout. qu''est-ce que tu veux ?','You''re not disturbing us at all. What do you want?'),
(33,4,'J''ai besoin d''une nouvelle robe d''été : aidez-moi à la choisir.','I need a new summer dress: help me to choose it.'),
(33,5,'Tu en as besoin, ou tu en as envie ? Ce n''est pas la même chose !','You need one or you want one? It''s not the same thing!'),
(33,6,'Je sais bien, mais quelle importance ? Je veux en acheter une.','I know [very] well, but what does it matter (what importance),? I want to buy one.'),
(33,7,'Je n''ai rien dans ma garde-robe. Tous mes vêtements sont vieux.','I have nothing in my wardrobe. All my clothes are old.'),
(33,8,'Bien, regardons en ligne. Tu connais ce site, mode.fr ?','Well, let''s look online. Do you know this site, mode.fr (fashion.fr),?'),
(33,9,'“Choisissez parmi des milliers de modèles pour trouver le vêtement de vos rêves”','“Choose among thousands of models to find the [item of] clothing of your dreams.”'),
(33,10,'C''est génial. Tu trouves tout : des robes, des jupes, des pulls, des manteaux.','It''s fantastic. You [can] find everything: dresses, skirts, jumpers, coats.'),
(33,11,'Ce n''est pas vraiment bon marché mais les prix sont raisonnables.','It''s not really cheap (good-market), but the prices are reasonable.'),
(33,12,'Regarde : ce chemisier est joli, n''est-ce pas ? Il existe en rouge, en bleu et en orange.','Look: this blouse is pretty, isn''t it? It comes in (exists), in red, blue, and orange.'),
(33,13,'Je cherche une robe verte, noire ou bleue, pas un chemisier orange ou jaune !','I''m looking for a green, black or blue dress, not an orange or yellow blouse!'),
(33,14,'Et celle-là ? qu''est-ce que tu en penses ? C''est très chic.','And this one? What do you think (of-it),? It''s very stylish.'),
(33,15,'Non, je ne vois rien qui m''intéresse. Mais merci quand même ! À demain.','No, I can''t see anything that interests me. But thank you all the (even), same! See you (to), tomorrow.');

CREATE VIEW courses AS
SELECT DISTINCT lesson,
       CASE WHEN lesson BETWEEN 1 and 3 THEN 1 ELSE 0 END AS free
FROM contents;